# ASP.NET

# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
  branches:
    include:
    - main
  paths:
    exclude:
    - azure-pipelines.yml
    
variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  poolName: 'Default'

stages:
- stage: Build
  displayName: Build stage
  
  jobs:
  - job: Build
    displayName: Build

    pool: $(poolName)

    steps:
    - task: DotNetCoreCLI@2
      inputs:
        command: 'build'
        projects: '**/BlazorConnectFour.csproj'

    - task: SonarQubePrepare@4
      inputs:
        SonarQube: 'Connect to sonarqube'
        scannerMode: 'MSBuild'
        projectKey: 'sonar_project'
    - task: SonarQubePublish@4
      inputs:
        pollingTimeoutSec: '300'
        projectName: 'Sonar connection'
        #do unit tests here 