# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
  branches:
    include:
    - main
  paths:
    exclude:
    - azure-pipelines.yml
    
variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  poolName: 'Default'


stages:
- stage: Build
  displayName: Build stage
  
  jobs:
  - job: Build
    displayName: Build

    pool: $(poolName)
    #pool: 
    #  vmImage: 'windows-latest'

    steps:
    

    # Prepare Analysys Configuration task
    - task: SonarQubePrepare@4
      inputs:
        SonarQube: 'connect_to_sonarqube'
        scannerMode: 'MSBuild'
        projectKey: 'unique_project_key'
        projectName: 'sonarqube_project'

    - task: DotNetCoreCLI@2
      inputs:
        command: 'build'
        projects: '**/BlazorConnectFour.BlazorConnectFour.csproj'
        modifyOutputPath: true

    # Run Code Analysis task
    - task: SonarQubeAnalyze@4

    # Publish Quality Gate Result task
    - task: SonarQubePublish@4
      inputs:
        pollingTimeoutSec: '300'
        
        # Put Unit tests here